travis:
  secure:
    BINSTAR_TOKEN: SBEIDYiEQX6l+GIfs6ay1MOcSpLnGXoGV+75AWnxg4ZfLDrUvKtJGV5f63ld1/QESG0o6c92u9v/omtm9HaZazfeKtbZIxHRxH0BlfDqn7HUNGhUTzIyXx93/cQZpEw1lWpPkSRY12KlDY14Sa8FvmGWIbpMdu6+yVyFNO78DpoGDvaxgaivFIzLh0S/9GgZuaNivPyCjA7LMgGSmw1FM9MZNhbtIwKZGtNyRoVYwXvTeNZk7GfGBGAP3HmknjxIos/RpeLlKN+RPNlxONSZ78cmRAkFumf0CDfDQZCkk48CNEjYhu3Q1ps7bJgME3eg6xIXrsV4SjKtMNwa7JP6eg1mRm6h3xuCnjS0ijlurf5pFwYtyyuyTGsVhIuABlTunCMNKbArwyBr+LR2Wv45n3T7xyP0WevSxM7EQaBijs4LaIWbJX/7WJC/cKl6xajPR1DKLtwgRE9ZhqVt/PT5cjfLrxOdJ5KmI87ShEd898vL+HFntQT5MMWEnVWz+i4Ee+Iq7TGU0ueGV078bnioZ+FKo0XybmUXsSHGI38X5yKmpOO/CRe5Q8Jx9qXO0BTtcQdlqEUKx8XVYQNKXePfXx8eb8iRMhnYe8ivXlpOgnWxGlPqypd825gusrWemtDVMskQeyx38arkRP2rh3QR/jhLvLe7BNIMk2c0dNXBncg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
