travis:
  secure:
    BINSTAR_TOKEN: ZyFIzN5sL7mctZzI49k9qEfSCsDw/9UtzVoRzJFGZiini6N8i/uuMiGClEsbb/vH6PPE/DiJPUg5oYpySMq6ik+9mvqVSAMGp3BIcKs/9pSzxQ8kWFwqMW0OmaOMERovk0iDHD1W/M5TrA/Gdy5+Po45+hI4uiRZBEfbR2bEemBkFOTrT2dh9c9WK8p1qeW3WdYe9YrMCLHrLWE9T4qfVViM/jM8/lBcWStX6n50LjI5cDOfNqROjqWDTtISzrf+JiTOJrlgWwG+sxy6aG7dAWnqeMBSEmh3NF33bEM3gO/ZwZnSzM97Z8avFd3bI3Cjb8s2E0RYJyiHqfR5HI1NGtjP2HpjyJMGH0vcH67OkPU1BdzH0PSP3hd+4WZwoPwu721+Dp7mCUkQ33dYC2XGs9ImhLKnoeKDJpt8aTExukiNtzs1m1NGqLWmXD/QJrsfzH1uqA1y7g22jvAAqjCrjw1ie5uW5Z/npq9tBf5JqEpHkj9CtHFpNAZ66EulOreEYYJXL+Rc9SSqq3j4ixpq8KOCpDokykMhS1dLy5dSkEWnnMPFTIPE9kEPrY3P6NLtujJss+y6XXkRcuOYC0Fukwcs71h+RbjoGq3/likbfNsbGRRgIiYjVbchsYw0Yklxmf3YFt97p13HgtiO9jj9um/d9GInEln/om5WBA4Hs9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
