travis:
  secure:
    BINSTAR_TOKEN: lyiZpm7zDT7bGn2wVbqucfSdYqHWn43Fovc2191Pqia/JPS21cABaa6NWPY5a2kWxOGOhPhpHGfeuONyZOwUF+CwxS3xTEoQP5cN1dmQU5DhcKXn2w8R+uhF2KGA+FNbZhJHztJ0rPij9oR22WLvD2ey4ppbabajvADRQ+s6Cw66oY1hSimcL40X9omnodWop+wyEj8lZQ/XlNer55Vyih5G3KRNjO8dsUjZtw1L14m7CUFVTdIE27ldLd49Nnb6RpDGysn66dOBY3Zp/IAo4vlXQ10HY+CT/+cMiwXfEb0Sg9Wh3FACJrrvIB0bQrWdXxS96QDZOQDtMUguj/hwBqzOIaeYwFc+h6hupYFD6jiTpHoWS8iTTBJhjGMyy8rAZfOw8IMWBTJrllQYGBtlFKhf7ThHJhZb0QWIysQYZ2ClLkAJtER7/+py5qNhS6bdeh/xnQVU1w5Ee0czh98yBxuU7mt8aPu139Ek25Z6L+pv4VMckkGLU4MzUV0J9Dr6ZyKNw4AimQxXY0mTxSCAx8pM/OSxsZFyC8moZ/VUg/5diAGFR7kSSY9axMfKlwfDZtsivko9Gl1CFDzbt36U8qSI0A62BX2BwlJRg9JuvHkIvjERDpMHJ4a5HBGKqFxXIImtVFuHCgMx1w6s1VjtgmRjlmFjZOjrvSOaoaunI38=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
