travis:
  secure:
    BINSTAR_TOKEN: VycM6cuavIUCeGlQt9FqH1VYzDhy+3skobIh1MuyfyoUkAxsnhrTCI580bf7fEjp1397PoKEXhvUb6V6UyZmF7JyNsO0EqodjMEDBsAw4AEMYaEikLToxZ+X7bZHJVqzGGpudOWCosM3ag6lTlMidzurS9pbCN1hE8xZFTI/0PybzobIHrdxGbseIunR3Oj2ZSBJV9VwWfOiTUCNbx2pASa0ZsPg8R2Qlq2DKR5eJ7EmAcQXKHztglN42wEQpcp3JDceM6+JvH+z4OHzkG32+KqDr3+R9drOH7mk12RW4uMT6Ht6/lKGYYNTJKe6BtFLV7+48DsxDKqy6QPVZYskz66/9+yUIsPJ8jTzKIFUSsy+SvM82TGp2v0XF4NbA/AvBusVguuMdzQL9UAsb+Mk+bEl5DbQ638o5kqvvIJuOb0JQPZWUwFAOBYSPZ/QVZAem+KbGuurDlTFu8lL7Mt5dVSLMgYSsKKlSV8CQ54ItGv8dtUePQMV+Uiic9alBxWLEqFOivuwtKic7NIsbiowZAoV9GaoGaymiqMTNy/X/nHBeocg7JDKv1zMcgrsqxde584pzng/HYBLrIJBzvnXydmTMjILqBCiKye4pYVXKc7/4AEnLQY4SlXDpJI5zWKJUakusNp10iPQIKVhr7hns1BGCwTwoyriuWnzCR77c/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
